# inastall and setup catalogue dependencies

- name: install nodejs in catalogue component
  hosts: catalogue
  become: yes

  tasks:
  - name: setup NodeJs repos 
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: install NodeJs
    ansible.builtin.yum:
      name: nodejs
      state: present 

  - name: check roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc !=0
    name: add roboshop user
    ansible.builtin.user:
      name: roboshop 

  - name: check /app directory exists or not
    ansible.builtin.stat: #stat is the module check the statistics of files and directories
      path: /app
    register: directory
  
  - name: print the directory
    ansible.builtin.debug:
      msg: "output: {{directory}}"

  - when: directory.stat.exists == False
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: download catalogue application artifact
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp 
  
  - name: extract catalogue artifact
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copy catalogue service 
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  
  - name: demon reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: present
  
  - name: Load catalogue schema
    ansible.builtin.command: mongo --host mongodb.awsdevopschandu.tk < /app/schema/catalogue.js
  
  - name: restart catalogue service 
    ansible.builtin.service:
      name: catalogue
      state: restarted
      enabled: true


  


