#mongodb install using ansible-playbook

- name: install and configure mongodb
  hosts: mongodb
  become: true

  tasks:
  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      state: present
  - name: start and enable the mongodb service 
    ansible.builtin.service:
      name: mongod
      state: started
      enabled: yes
  - name: edit the conf file and replace old hostname with new hostname
    ansible.builtin.replace:
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'
  - name: restart mongodb
    ansible.builtin.service:
      name: mongod
      state: restarted


    


