#mongodb install using ansible-playbook

- name: install and configure mongodb
  hosts: mongodb
  become: true

  tasks:
  - name: copy mongo repo to yum.repos.d, Setup the MongoDB repo file
    ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.yum:
      name: mongodb-org
      status: present
    


